"""
Alert Manager for NetGuard.

Handles deduplication, cooldown suppression, IP whitelisting, and persistence
of security alerts into an embedded SQLite database.
"""
import json
import logging
import sqlite3
import threading
import time
from typing import Any, Callable, Dict, List, Optional

from netguard.config import AlertsConfig
from netguard.models import Alert

logger = logging.getLogger("netguard.alerts")


class AlertManager:
    """
    Manages the lifecycle of alerts generated by detection rules.

    Features:
    - Cooldown: Suppresses repetitive alerts for the same (attack_type, src_ip) within N seconds.
    - Whitelisting: Ignores alerts originating from trusted infrastructure (e.g., gateway, DNS).
    - Persistence: Automatically records alerts to SQLite for audit trails and UI retrieval.
    - In-memory event dispatching to WebSocket listeners.
    """

    def __init__(
        self,
        config: Optional[AlertsConfig] = None,
        on_alert_dispatched: Optional[Callable[[Alert], None]] = None,
    ):
        self.config = config or AlertsConfig()
        self.on_alert_dispatched = on_alert_dispatched
        self.cooldown_seconds = self.config.cooldown_seconds
        self.whitelist = set(self.config.whitelist_ips)
        self.db_path = self.config.db_path
        self._lock = threading.Lock()

        # Cooldown map: (attack_type, src_ip) -> last_fired_timestamp
        self._last_alert_time: Dict[tuple, float] = {}
        # Blacklisted IPs (blocked attackers)
        self._blacklist: set = set()

        self._init_db()

    def _init_db(self):
        """Initializes SQLite alerts and blacklist tables."""
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.cursor()
            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS alerts (
                    id TEXT PRIMARY KEY,
                    ts REAL NOT NULL,
                    type TEXT NOT NULL,
                    severity TEXT NOT NULL,
                    src_ip TEXT NOT NULL,
                    dst_ip TEXT NOT NULL,
                    summary TEXT NOT NULL,
                    evidence TEXT NOT NULL,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
                """
            )
            cursor.execute(
                "CREATE INDEX IF NOT EXISTS idx_alerts_ts ON alerts (ts DESC)"
            )
            cursor.execute(
                "CREATE INDEX IF NOT EXISTS idx_alerts_sev ON alerts (severity)"
            )
            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS blacklist (
                    ip TEXT PRIMARY KEY,
                    reason TEXT NOT NULL DEFAULT '',
                    added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
                """
            )
            conn.commit()
            # Load persisted blacklist into the in-memory whitelist set
            cursor.execute("SELECT ip FROM blacklist")
            for row in cursor.fetchall():
                self._blacklist.add(row[0])

    def should_suppress(self, alert: Alert, now: Optional[float] = None) -> bool:
        """Determines if an alert should be dropped due to whitelist or cooldown."""
        current_time = now if now is not None else alert.ts

        # 1. Whitelist check
        if alert.src_ip in self.whitelist:
            return True

        # 2. Cooldown check per (type, src_ip)
        key = (alert.type, alert.src_ip)
        with self._lock:
            last_time = self._last_alert_time.get(key, 0.0)
            if current_time - last_time < self.cooldown_seconds:
                return True
            self._last_alert_time[key] = current_time

        return False

    def handle_alert(self, alert: Alert, now: Optional[float] = None) -> bool:
        """
        Processes an alert: checks cooldown/whitelist, saves to database,
        and broadcasts to dispatch listeners.
        Returns True if alert was accepted and dispatched, False if suppressed.
        """
        if self.should_suppress(alert, now=now):
            logger.debug("Suppressed alert (%s from %s) via cooldown/whitelist", alert.type, alert.src_ip)
            return False

        logger.warning(
            "ALERT [%s] %s -> %s: %s",
            alert.severity,
            alert.type,
            alert.dst_ip,
            alert.summary,
        )

        # 1. Persist to SQLite
        try:
            with sqlite3.connect(self.db_path) as conn:
                cursor = conn.cursor()
                cursor.execute(
                    """
                    INSERT INTO alerts (id, ts, type, severity, src_ip, dst_ip, summary, evidence)
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                    """,
                    (
                        alert.id,
                        alert.ts,
                        alert.type,
                        alert.severity,
                        alert.src_ip,
                        alert.dst_ip,
                        alert.summary,
                        json.dumps(alert.evidence),
                    ),
                )
                conn.commit()
        except Exception as e:
            logger.error("Failed to persist alert to SQLite: %s", e)

        # 2. Dispatch to WebSocket listeners
        if self.on_alert_dispatched:
            try:
                self.on_alert_dispatched(alert)
            except Exception as e:
                logger.error("Failed to dispatch alert: %s", e)

        return True

    def get_alerts(self, limit: int = 50, severity: Optional[str] = None) -> List[Dict[str, Any]]:
        """Retrieves recent alerts from SQLite."""
        query = "SELECT id, ts, type, severity, src_ip, dst_ip, summary, evidence FROM alerts"
        params = []

        if severity:
            query += " WHERE severity = ?"
            params.append(severity.upper())

        query += " ORDER BY ts DESC LIMIT ?"
        params.append(limit)

        results = []
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.cursor()
            cursor.execute(query, params)
            for row in cursor.fetchall():
                try:
                    evidence_parsed = json.loads(row[7])
                except Exception:
                    evidence_parsed = {}

                results.append({
                    "id": row[0],
                    "ts": row[1],
                    "type": row[2],
                    "severity": row[3],
                    "src_ip": row[4],
                    "dst_ip": row[5],
                    "summary": row[6],
                    "evidence": evidence_parsed,
                })

        return results

    def clear_alerts(self):
        """Purges stored alerts."""
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.cursor()
            cursor.execute("DELETE FROM alerts")
            conn.commit()
        with self._lock:
            self._last_alert_time.clear()

    def get_alert_stats(self) -> Dict[str, Any]:
        """Returns alert counts grouped by type and severity."""
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.cursor()
            cursor.execute("SELECT type, COUNT(*) FROM alerts GROUP BY type")
            by_type = {row[0]: row[1] for row in cursor.fetchall()}
            cursor.execute("SELECT severity, COUNT(*) FROM alerts GROUP BY severity")
            by_severity = {row[0]: row[1] for row in cursor.fetchall()}
            cursor.execute("SELECT COUNT(*) FROM alerts")
            total = cursor.fetchone()[0]
        return {"total": total, "by_type": by_type, "by_severity": by_severity}

    # --- IP Blacklist Management ---

    def add_to_blacklist(self, ip: str, reason: str = "") -> bool:
        """Adds an IP to the blacklist. Returns True if newly added."""
        with self._lock:
            if ip in self._blacklist:
                return False
            self._blacklist.add(ip)
        try:
            with sqlite3.connect(self.db_path) as conn:
                conn.execute(
                    "INSERT OR IGNORE INTO blacklist (ip, reason) VALUES (?, ?)",
                    (ip, reason),
                )
                conn.commit()
        except Exception as e:
            logger.error("Failed to persist blacklist entry: %s", e)
        return True

    def remove_from_blacklist(self, ip: str) -> bool:
        """Removes an IP from the blacklist."""
        with self._lock:
            if ip not in self._blacklist:
                return False
            self._blacklist.discard(ip)
        try:
            with sqlite3.connect(self.db_path) as conn:
                conn.execute("DELETE FROM blacklist WHERE ip = ?", (ip,))
                conn.commit()
        except Exception as e:
            logger.error("Failed to remove blacklist entry: %s", e)
        return True

    def get_blacklist(self) -> List[Dict[str, Any]]:
        """Returns all blacklisted IPs."""
        results = []
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.cursor()
            cursor.execute("SELECT ip, reason, added_at FROM blacklist ORDER BY added_at DESC")
            for row in cursor.fetchall():
                results.append({"ip": row[0], "reason": row[1], "added_at": row[2]})
        return results

    def is_blacklisted(self, ip: str) -> bool:
        with self._lock:
            return ip in self._blacklist
